### ISSUE TITLE
privateChartsRepo functionality if not working

### ISSUE THREAD

**Issue by kewlvishnu** [microsoft/helm-web-api#8]
### Steps to Replicate:
`curl -d '{"chartName":"chart-name", "releaseName":"chart-name-1", "privateChartsRepo":"https://<gs-bucket-name-helm-repo>.storage.googleapis.com/index.yaml"}' -H "Content-Type: application/json" -X POST http://<service-endpoint>:4000/install`

### Expected behavior:
`should return success`

### Actual result:
`{"status":"failed","reason":"Installation failed."}`

**Comment by eladiw** [comment]
Thanks for opening this issue. I will check it out

**Comment by eladiw** [comment]
Clone of #7
